### ISSUE TITLE
IndexError when trying to add another waypoint to data.csv

### ISSUE THREAD

**Issue by wrongsyntax** [wrongsyntax/AStar#6]
```
Traceback (most recent call last):
  File "[...]/AStar/tree.py", line 136, in <module>
    waypoints, nofly_region = create_safe_waypoints(parsed_nodes)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/AStar/tree.py", line 63, in create_safe_waypoints
    safe_waypoints[name] = (safe_region.vertices[i].x, safe_region.vertices[i].y)
                            ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Occurred when attempting to add a new obstacle node 'F' at the end of `data.csv`.

**Comment by wrongsyntax** [comment]
Seems to only happen sometimes, depending on the coordinates.

More testing required.

**Comment by wrongsyntax** [comment]
Found that this occurs due to the fact that the `convex_hull` created by Sympy ignores points that would make the polygon non-convex. This part of the code was trying to add a safe_waypoint version of every node originally given based on the vertices of the `safe_region`, but since there were now less vertices than original nodes, it caused an index error when the program attempted to add unused nodes into `safe_waypoints` because there was no corresponding vertex.
